version: "2"

linters:
  default: standard
  enable:
    - misspell
    - revive
    - perfsprint
    - godot
    - dupword
    - usestdlibvars
    - intrange
    - thelper
  settings:
    revive:
      rules:
        - name: exported
          disabled: false
    godot:
      scope: declarations
      period: true

formatters:
  enable:
    - gofumpt
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/retailnext/tfref)

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
